package javaapplication2;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Rectangle;
import java.util.Vector;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
/**
 *
 * @author Margaret.Wang
 */
public class BookInfoJFrame extends javax.swing.JFrame {

    /**
     * Creates new form BookInfoJFrame
     */
    Vector data=new Vector();
    Vector title=new Vector();
    DefaultTableModel dtm=new DefaultTableModel();
    JTable tbl=new JTable(dtm);
    JTableHeader jTableHeader1 = tbl.getTableHeader();
    int index=0;
    int type=1;
    
    public BookInfoJFrame() {
        initComponents();
        tbl.setBounds(new Rectangle(3,250,500,100));
        jTableHeader1.setBounds(new Rectangle(3,220,500,30));
        getContentPane().add(jTableHeader1);
        getContentPane().add(tbl);
        showTextFieldData(1);
        showTableData();
       // tbl.addMouseListener(new java.awt.event.MouseAdapter() {
        //    public void mouseClicked(java.awt.event.MouseEvent evt) {
         //       tblMouseClicked(evt);
         //   }
       // });
    }
public void showTextFieldData(int index){
        data=DBCon.queryData("use BookDB Select * from Book");
        if(data.size()>0){
            BookInfo b1 = new BookInfo();
            Vector vBo= (Vector) data.get(index);
            Vector line = (Vector) data.get(type);
            if(!line.isEmpty()){
            ID.setText(line.get(0).toString());
            name.setText(line.get(1).toString());
            author.setText(line.get(2).toString());
            press.setText(line.get(3).toString());
            pressdate.setText(line.get(4).toString());
            b1.getBookInfo(vBo);
            ID.setText(b1.BookID);
            name.setText(b1.BookName);
            author.setText(b1.Author);
            press.setText(b1.Press);
            pressdate.setText(b1.PressDate);
            
            if (line.get(5).toString().equals("在库")) {
                in.setSelected(true);
            } else {
                out.setSelected(true);
            }
            author.setText(b1.Author);
        }else{ 
            clearAll();
            JOptionPane.showMessageDialog(null,"没有数据","警告", JOptionPane.INFORMATION_MESSAGE);
        }
        }
        lock();
    }

public void showTableData(){
        title.add("图书编号");
        title.add("书名");
        title.add("作者");
        title.add("出版社");
        title.add("出版日期");
        data=DBCon.queryData("Select * from Book");
        dtm.setDataVector(data,title);
    }
    public void clearAll(){
        ID.setText("");
        name.setText("");
        author.setText("");
        in.setSelected(true);
    }
    public void lock(){
        ID.setEnabled(false);
        name.setEnabled(false);
        author.setEnabled(false);
        press.setEnabled(false);
        pressdate.setEnabled(false);
        in.setEnabled(false);
        out.setEnabled(false);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        Add.setEnabled(true);
        Edit.setEnabled(true);
        Delete.setEnabled(true);
        Save.setEnabled(false);
    }
        public void unlock(){
        ID.setEnabled(true);
        name.setEnabled(true);
        author.setEnabled(true);
        press.setEnabled(true);
        pressdate.setEnabled(true);
        in.setEnabled(true);
        out.setEnabled(true);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        Add.setEnabled(false);
        Edit.setEnabled(false);
        Delete.setEnabled(false);
        Save.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        author = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        press = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pressdate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        in = new javax.swing.JRadioButton();
        out = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("图书编号:");
        jLabel1.setToolTipText("");

        jLabel2.setText("书名:");

        jLabel3.setText("作者:");

        jLabel4.setText("出版社:");

        jLabel5.setText("出版日期:");

        jLabel6.setText("状态:");

        buttonGroup1.add(in);
        in.setText("在库");

        buttonGroup1.add(out);
        out.setText("借出");

        jButton2.setLabel("<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setLabel(">");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Add.setText("添加");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Edit.setText("修改");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        Delete.setText("删除");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Save.setText("保存");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pressdate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name)
                                    .addComponent(press)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(in)
                                .addGap(28, 28, 28)
                                .addComponent(out)
                                .addGap(84, 84, 84))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(54, 54, 54)
                                    .addComponent(jButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton3))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Add)
                                    .addGap(28, 28, 28)
                                    .addComponent(Edit)
                                    .addGap(21, 21, 21)
                                    .addComponent(Delete)
                                    .addGap(18, 18, 18)
                                    .addComponent(Save))))
                        .addGap(0, 237, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(press, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pressdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(out)
                    .addComponent(in))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add)
                    .addComponent(Edit)
                    .addComponent(Delete)
                    .addComponent(Save))
                .addContainerGap(198, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        index--;
        if(index>=0)
            showTextFieldData(index);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        index++;
        if(index<data.size())
            showTextFieldData(index);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        unlock();
        clearAll();
        type=1;
    }//GEN-LAST:event_AddActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
       unlock();
       ID.setEnabled(false);
       type = 2;
    }//GEN-LAST:event_EditActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null,"你确定要删除该数据吗？","确认删除",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==JOptionPane.YES_OPTION){
            String BookID=ID.getText();
            String sql="delete from BookInfo where BookID='"+BookID+"'";
            if(DBCon.updateData(sql)){
                data=DBCon.queryData("Select * from Book");
                dtm.setDataVector(data,title);
                JOptionPane.showMessageDialog(null,"删除数据成功!","警告", JOptionPane.INFORMATION_MESSAGE);
                showTextFieldData(0);
            }
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        String BookID=ID.getText();
        String BookName=name.getText();
        String Author=author.getText();
        String Press=press.getText();
        String PressDate=pressdate.getText();
        String Status="";
        if(in.isSelected()){
            Status="在库";
        }else if(out.isSelected()){
            Status="借出";
        }
        String sql="";
        switch(type){
            case 1:
                sql="insert into Book values('"+ BookID +"','"
                      +BookName +"','"+Author +"','"+ Press+",'"+PressDate+"','"+Status+"')";
                break;
            case 2:
                sql="update Book set BookName='"+BookName +"',Status='"+Status 
                   +"',Press='"+Press +"',PressDate='"+PressDate +"',Author='"+ Author+"' where BookID='"+BookID+"'";
                break;
        }
                
        if(DBCon.updateData(sql)){
            data=DBCon.queryData("Select * from Book");
            dtm.setDataVector(data,title);
            lock();
            JOptionPane.showMessageDialog(null,"保存数据成功!","警告", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_SaveActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookInfoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookInfoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookInfoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookInfoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookInfoJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Edit;
    private javax.swing.JTextField ID;
    private javax.swing.JButton Save;
    private javax.swing.JTextField author;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton in;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField name;
    private javax.swing.JRadioButton out;
    private javax.swing.JTextField press;
    private javax.swing.JTextField pressdate;
    // End of variables declaration//GEN-END:variables
}